### ISSUE TITLE
Failure to define species causes error during setup

### ISSUE THREAD

**Issue by degorius** [Olen/homeassistant-plant#1]
If `species` is not included in the config file I get the following error instead of a default value being used.
Giving even a gibberish value, eg. Poo Flower for `species` works fine.

```
ERROR (MainThread) [homeassistant.setup] Error during setup of component plant
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/home/homeassistant/.homeassistant/custom_components/plant/__init__.py", line 164, in async_setup
    entity = Plant(plant_name, plant_config)
  File "/home/homeassistant/.homeassistant/custom_components/plant/__init__.py", line 244, in __init__
    self._species = self._config.get(CONF_SPECIES).lower().replace("_", " ")
AttributeError: 'NoneType' object has no attribute 'lower'
```
Works great otherwise
  Thanks for the hard work

**Comment by Olen** [comment]
Thanks. I'll have a look at this during the holidays.

**Comment by elektrinis** [comment]
I have this problem as well.
How do I provide the initial value?

**Comment by Olen** [comment]
Thanks.
Did a quick fix and push now.  Should take care of the problem.

**Comment by elektrinis** [comment]
This works, thank you.
