### ISSUE TITLE
2023.11.0b1 errors

### ISSUE THREAD

**Issue by fhornrudd** [Olen/homeassistant-plant#109]
Handful of errors after updating core to latest beta. First out is this:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:696
First occurred: 4:51:31 PM (2 occurrences)
Last logged: 4:51:46 PM

Update for plant.aloe_vera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/__init__.py", line 637, in update
    if float(moisture) < float(self.min_moisture.state):
                               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'

**Comment by fhornrudd** [comment]
Fixed with 2023.10.3
