### ISSUE TITLE
After update 2023.11.0 got errors and entities is unavailable

### ISSUE THREAD

**Issue by VikeDragon** [Olen/homeassistant-plant#110]
After update 2023.11.0 got errors and entities is unavailable :

2023-11-02 16:01:18.727 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform plant.number: Platform not found (No module named 'homeassistant.util.temperature').

2023-11-02 16:04:27.317 ERROR (MainThread) [homeassistant.helpers.entity] Update for plant.asplenium fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/__init__.py", line 730, in update
    ) < float(self.min_dli.state):
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'

and so on by every plant

**Comment by VikeDragon** [comment]
Reinstalled the integration - it solved the problem
