### ISSUE TITLE
Detected blocking call in HA 2024.10.0b0

### ISSUE THREAD

**Issue by gieljnssns** [Olen/homeassistant-plant#197]
```
Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 10:51:37 (1 occurrences)
Last logged: 10:51:37

Detected blocking call to import_module with args ('custom_components.plant.group',) in /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 108, in _async_process_integration_platforms_for_component platforms = await integration.async_get_platforms(platforms_that_exist) File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")
```

**Comment by chemelli74** [comment]
Updated log for 2024.10.0:

```
2024-10-03 09:32:24.112 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.plant.group',) in /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
```

**Comment by hmmbob** [comment]
And 2024.10.1:

```
2024-10-05 15:45:02.677 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.plant.group',) in /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 108, in _async_process_integration_platforms_for_component
platforms = await integration.async_get_platforms(platforms_that_exist)
File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
platforms.update(self._load_platforms(platform_names))
File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
platform_name: self._load_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
```

**Comment by Olen** [comment]
But this bug refers to the core homeassitant, not this module.

There are no traces of "import_module" or anything like it in this integration as far as I can tell.
The `group.py` in this integration is basically a copy of the one in the documenation:
https://developers.home-assistant.io/blog/2024/05/10/group-integration/

So I have no idea what HA complains about here

**Comment by bdraco** [comment]
Since its overriding the core namespace its not loading it.

You can work around it by importing `group` in `__init__.py`

**Comment by Olen** [comment]
Thanks for the hint, but I am not sure what you mean.

Is there anything special with `group`, as it seems to work fine for stuff like sensors and numbers etc.

From the error, it seems like HA is trying to import it, at least it refers to custom_components.plant here:
`Detected blocking call to import_module with args ('custom_components.plant.group',)`

How should it be imported if not with that path?

**Comment by chemelli74** [comment]
@Olen can you kindly release a beta with the fix ?

**Comment by hmmbob** [comment]
I've applied the patch manually to my system and can confirm the issue is resolved
