### ISSUE TITLE
Error: Update for plant.****** fails

### ISSUE THREAD

**Issue by milandzuris** [Olen/homeassistant-plant#212]
Hi i have many times this in the Logs
Version? 2024.11.0

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:960
First occurred: December 15, 2024 at 16:06:16 (6654 occurrences)
Last logged: 19:51:13

Update for plant.rock_garden_island fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1320, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plant/__init__.py", line 745, in update
    and self.dli.state is not None
        ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 556, in state
    unit_of_measurement = self.unit_of_measurement
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 537, in unit_of_measurement
    := self.platform.default_language_platform_translations.get(translation_key)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'default_language_platform_translations'
```

**Comment by syphernl** [comment]
Appears to be the same issue as https://github.com/Olen/homeassistant-plant/issues/210
