### ISSUE TITLE
DLI missing after upgrade to HA core 2023.4b

### ISSUE THREAD

**Issue by thatslolo** [Olen/homeassistant-plant#65]
I find the following log line for every plant:

`2023-03-31 12:18:26.321 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up plant platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/plant/sensor.py", line 129, in async_setup_entry
    pdli = PlantDailyLightIntegral(hass, entry, pintegral, plant)
  File "/config/custom_components/plant/sensor.py", line 533, in __init__
    super().__init__(
TypeError: UtilityMeterSensor.__init__() missing 1 required keyword-only argument: 'periodically_resetting'`

**Comment by tbrasser** [comment]
https://github.com/Olen/homeassistant-plant/pull/67  created a PR

**Comment by Olen** [comment]
Released a new version which should fix this.
