### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by krizzziz** [Olen/homeassistant-plant#76]
The plant entity on my HA is not working fully correct. I do see it has all of the variables:

`species: Olea europaea
moisture_status: ok
temperature_status: ok
conductivity_status: Low
illuminance_status: ok
humidity_status: null
dli_status: Low
species_original: olea europaea
device_class: plant
entity_picture: /local/images/plants/olea europaea.jpg
friendly_name: Olijfboom1 `

but the plantcard is not displaying anything. It’s blank. When diving into the logs I could see the following:

`ValueError: Sensor sensor.olijfboom1_soil_moisture has device class moisture, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>) `

so maybe this has to do something with my plant entity not showing up correctly?

**Comment by Zriel88** [comment]
Same here

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 781, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plant/__init__.py", line 627, in update
    and self.sensor_moisture.state != STATE_UNKNOWN
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.limonero_soil_moisture has device class moisture, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>)
```

**Comment by theOrakle** [comment]
Ditto

**Comment by Ucsus** [comment]
same

**Comment by Ucsus** [comment]
> same

[replace_sensor](https://github.com/Olen/homeassistant-plant/issues/42) helped
