### ISSUE TITLE
2.1.2-beta1 not working

### ISSUE THREAD

**Issue by Jano1312** [Olen/homeassistant-plant#79]
With 2.1.2-beta1 i get the following error when starting homeassistant:

```
Logger: homeassistant.setup
Source: components/plant/__init__.py:110
First occurred: 00:24:55 (1 occurrences)
Last logged: 00:24:55
Error during setup of component plant

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/plant/__init__.py", line 110, in async_setup
    for plant_name, plant_config in config[DOMAIN].items():
                                    ~~~~~~^^^^^^^^
KeyError: 'plant'
```

found this in the logfile:
```
2023-06-18 00:34:11.249 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'plant' does not have a valid version key (2.1.2beta1) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`
```

to troubleshoot i changed in the manifest file 2.1.2beta1 to 2.1.2
Now its starting when i restart, but sensors still not updating and i get the following in the logfile:

```
2023-06-18 01:04:53.664 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547670605776] Error handling message: Unknown error (unknown_error) Jano from 192.168.178.98 (Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 186, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/plant/__init__.py", line 302, in ws_get_info
    connection.send_result(msg["id"], {"result": plant_entity.websocket_info})
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/__init__.py", line 463, in websocket_info
    ATTR_CURRENT: self.sensor_temperature.state or STATE_UNAVAILABLE,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.schwertfarn_temperature has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>)
2023-06-18 01:04:53.681 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547670605776] Error handling message: Unknown error (unknown_error) Jano from 192.168.178.98 (Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 186, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/plant/__init__.py", line 302, in ws_get_info
    connection.send_result(msg["id"], {"result": plant_entity.websocket_info})
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/__init__.py", line 463, in websocket_info
    ATTR_CURRENT: self.sensor_temperature.state or STATE_UNAVAILABLE,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.zierspargel_temperature has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>)
2023-06-18 01:04:53.691 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547670605776] Error handling message: Unknown error (unknown_error) Jano from 192.168.178.98 (Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 186, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/plant/__init__.py", line 302, in ws_get_info
    connection.send_result(msg["id"], {"result": plant_entity.websocket_info})
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/__init__.py", line 463, in websocket_info
    ATTR_CURRENT: self.sensor_temperature.state or STATE_UNAVAILABLE,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.livistona_rotundifolia_temperature has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>)
2023-06-18 01:05:29.825 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.wohnraum (<class 'custom_components.better_thermostat.climate.BetterThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
```

And now, not sure why, i dont get any errors anymore but also no updates. I continue to search for any problems and report if i find anything

**Comment by Jano1312** [comment]
After replacing all sensors manually, everything is working as expected
