### ISSUE TITLE
Cannot set up 

### ISSUE THREAD

**Issue by leeandy1** [Olen/homeassistant-plant#80]
I have just installed this integration but am getting the following error:

`This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/plant/plant_helpers.py:105
Integration: Plant monitor (documentation, issues)
First occurred: 8:52:19 PM (1 occurrences)
Last logged: 8:52:19 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 297, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 393, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/config_flow.py", line 115, in async_step_user
    return await self.async_step_select_species()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/config_flow.py", line 186, in async_step_select_species
    search_result = await plant_helper.openplantbook_search(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/plant_helpers.py", line 105, in openplantbook_search
    plant_search = await self.hass.services.async_call(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ServiceRegistry.async_call() got an unexpected keyword argument 'limit'
`
I'm running Home Assistant 2023.7

**Comment by stevewull** [comment]
I also just installed the integration. I am getting the same error when adding a plant entry.

If I leave species blank, I can successfully create a plant by manually entering the values.

If I enter a species when creating a plant, thus invoking a lookup in plantbook, I receive the error.

**Comment by Olen** [comment]
Added a quick fix to the master branch here.  Need to test it before I release an upgrade, but you can fix this by removing the "limit" from line 110 in plant_helpers.py

**Comment by JulienNabaztag** [comment]
and line 145 too, by the way I don't understand how it works
I'm trying to put "Beaucarnea recurvata" as Species and it doesn't works
so what I have to put in this case ? https://open.plantbook.io/api/v1/plant/detail/beaucarnea%20ecurvata/
Maybe it can be usefull to load directly a json file, as expert mode

**Comment by Olen** [comment]
Created a beta release with the fixes for 2023.7

Thinking about using the new service call return values instead of abusing sensors with the results.
But that will be later.

**Comment by leeandy1** [comment]
I have updated to the beta version and now the plant is set up. I am also now having the same issue as @JulienNabaztag in that it cannot find my plant but the plant exists in open plant book. I have added the details manually for now and it seems to be working fine.

**Comment by cromelex** [comment]
Been using this for a while but added a new plant today and was hit with the same error. Installed the BETA, and now can add the plant but it wont find existing plants in Open Plant Book (using the open plant book service returns the plant name correctly).
