### ISSUE TITLE
Unknown error creating a new plant

### ISSUE THREAD

**Issue by TBail** [Olen/homeassistant-plant#88]
I tried to create an new plant an getting an unknown error.

<img width="464" alt="image" src="https://github.com/Olen/homeassistant-plant/assets/40339145/66c0403c-70ed-45bb-bae2-81fb4640956b">

The log shows the following

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: aiohttp.server
Source: custom_components/plant/plant_helpers.py:105
Integration: Plant Monitor (documentation, issues)
First occurred: 18:50:36 (2 occurrences)
Last logged: 18:53:18

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 297, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 393, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/config_flow.py", line 115, in async_step_user
    return await self.async_step_select_species()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/config_flow.py", line 186, in async_step_select_species
    search_result = await plant_helper.openplantbook_search(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/plant_helpers.py", line 105, in openplantbook_search
    plant_search = await self.hass.services.async_call(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ServiceRegistry.async_call() got an unexpected keyword argument 'limit'

<img width="304" alt="image" src="https://github.com/Olen/homeassistant-plant/assets/40339145/3714c39f-e9cc-4bc0-b6c6-2c0961441cfe">

**Comment by Luth1ng** [comment]
Same problem here...

**Comment by lkshrk** [comment]
fixed with https://github.com/Olen/homeassistant-plant/pull/87

**Comment by Olen** [comment]
I just released a new beta of both this, and the openplantbook-integration.
Please test the betas, and respond if something still does not work.

**Comment by TBail** [comment]
I was able to create a new plant with all data. so it seems to work.

Thanks a lot.
