### ISSUE TITLE
ValueError in HA log

### ISSUE THREAD

**Issue by tieskuh** [Olen/homeassistant-plant#94]
I have some error's in my HA Logs. Running the latest version of the integration and latest version of HA.

Home Assistant 2023.8.0
Supervisor 2023.07.1
Operating System 10.4
Frontend-versie: 20230802.0 - latest
Plant integration: v2.2.0

The sensor seems to be available and stable:

<img width="401" alt="image" src="https://github.com/Olen/homeassistant-plant/assets/115901851/61cc774d-b920-4c55-ac5c-ba5f1f4573dc">

Everything seems to work fine. I just can't figure out what the error is about.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/sensor/__init__.py:595
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:46:34 (811 occurrences)
Last logged: 20:49:14

[548168534848] Error handling message: Unknown error (unknown_error) iPad from x.x.x.x (Mozilla/5.0 (iPad; CPU OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.4 (io.robbie.HomeAssistant; build:2023.460; iPadOS 16.6.0) Mobile/HomeAssistant, like Safari)
[547769602112] Error handling message: Unknown error (unknown_error) XX from x.x.x.x (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
[547436036672] Error handling message: Unknown error (unknown_error) XX from x.x.x.x (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
[547582225472] Error handling message: Unknown error (unknown_error) XX from x.x.x.x (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 593, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 206, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/plant/__init__.py", line 302, in ws_get_info
    connection.send_result(msg["id"], {"result": plant_entity.websocket_info})
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/plant/__init__.py", line 463, in websocket_info
    ATTR_CURRENT: self.sensor_temperature.state or STATE_UNAVAILABLE,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 595, in state
    raise ValueError(
ValueError: Sensor sensor.ficus_lyrata_temperature has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unavailable' (<class 'str'>)

```

**Comment by Olen** [comment]
Yeah.  They turn up when the external sensor reports "unknown" or "unavailable"  - which it should not.  Especially when starting HA.
I dug a bit more and added a few try/excepts that seems to have helped here at least.

#95

**Comment by tieskuh** [comment]
Thanks for the quick fix!
